name: Basic MLOps CI/CD

on:
  push:
    paths:
      - 'Basic_CICD_Project/**'
  pull_request:
    paths:
      - 'Basic_CICD_Project/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Basic_CICD_Project

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest test_app.py

      - name: Lint Code
        run: |
          pip install flake8
          flake8 app.py

      # Optional: Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t basic-cicd-image .

      # Optional: Upload artifact if needed
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: model-or-output
      #     path: path/to/output/
